{
 "title": "Workers Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{job=\"node-exporter-worker\"})"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",job=\"node-exporter-worker\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter-worker\"})"
    }
   ]
  },
  {
   "title": "CPU Usage Per Worker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\", job=\"node-exporter-worker\"}[1m])))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "CV CPU Usage",
   "type": "graph",
   "description": "Coefficient of variation of CPU usage per worker",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "stddev(sum by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\", job=\"node-exporter-worker\"}[1m]))) / avg(sum by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\", job=\"node-exporter-worker\"}[1m])))",
     "legendFormat": "CV"
    }
   ]
  },
  {
   "title": "Memory Usage Per Worker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{job=\"node-exporter-worker\"}-node_memory_MemFree_bytes{job=\"node-exporter-worker\"}-node_memory_Cached_bytes{job=\"node-exporter-worker\"} - node_memory_Buffers_bytes{job=\"node-exporter-worker\"} - node_memory_Slab_bytes{job=\"node-exporter-worker\"})",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}