global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'node-exporter-worker'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter-worker'
        type: 'A'
        port: 9100
  - job_name: 'node-exporter-client'
    static_configs:
      - targets: ['node-exporter-client:9100']
